import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import RootProvider from "@/providers/RootProvider";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(manrope.className, "antialiased text-dark")}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
